ARG RUBY_VERSION=3.4.2
ARG NODE_VERSION=22.7.0

# Use Node image so we can pull the binaries from here.
FROM node:$NODE_VERSION AS node

# Ruby build image.
FROM ruby:${RUBY_VERSION}-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential libssl-dev libpq-dev git libsasl2-dev libyaml-dev curl && \
    rm -rf /var/lib/apt/lists/*

# Copy node binaries from node image.
COPY --from=node /usr/local /usr/local
COPY --from=node /opt /opt

# Setup environment variables.
ENV WORK_ROOT=/src
ENV APP_HOME=$WORK_ROOT/app/
ENV LANG=C.UTF-8
ENV RAILS_ENV=test
ENV POSTGRES_HOST=db
ENV POSTGRES_USER=postgres

# Create app directory.
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

RUN gem install bundler

# Copy dependencies files and install libraries.
COPY package.json yarn.lock .yarnrc.yml ./

RUN corepack enable
RUN yarn install --immutable && yarn cache clean

COPY Gemfile Gemfile.lock .ruby-version ./
RUN bundle install -j 4

COPY . .

RUN yarn build

# The default command will run RSpec
CMD ["bundle", "exec", "rspec"] 